---
title: "Working notes for Package__Multi_Logistic_Regression project"
author:
 - First Name, Last Name
output: pdf_document
fontsize: 12pt
---
   
# My first Idea
Initialisation du répertoire de travail courant et chargement des packages nécessaires
```{r}
setwd(dirname(rstudioapi::getSourceEditorContext()$path))
source(file.path('..','src','charger_packages.R'))
pkgLoad(c("R6")) # PUT THE PACKAGES YOU NEED TO INSTALL
```

```{r}
# library(R6)
# Logistic_Regression <- R6CLass("Logistic Regression",
#                                )
```

```{r}
data("Orange")
# Orange$index <- seq(from=1,to=length(Orange[,1]), by=1)

library(dplyr)
library(caret)




train_test_split <- function(data, target_name, test_size=NULL, seed=NULL){
    regressors <- select(data, -target_name)
    target <- as.factor(data[target_name])
    set.seed(seed)
    train_idx <- createDataPartition(y=target,p=1-test_size, list=FALSE, times=1)
    X_train <- regressors[train_idx,]
    X_test <- regressors[-train_idx,]
    y_train <- target[train_idx]
    y_test <- target[-train_idx]
    
    return(list(X_train = X_train, X_test = X_test, y_train = y_train, y_test = y_test))
}



res <- train_test_split(Orange, "Tree", test_size=0.3, seed=0)
X_train <- res$X_train
X_test <- res$X_test
y_train <- res$y_train
y_test <- res$y_test
```

```{r}
source(file.path("..","src","preprocessing.R"))

df <- data.frame(
  color = c("red", "blue", "green", "red"),
  length = c(4, 4, 20, 15)
)

af <- afdm$new()

af$fit_transform(df)
```

```{r}
df <- data.frame(
  color = c("red", "blue", "green", "red"),
  size = c("small", "medium", "large", "medium")
)

data.frame(row.names = seq(1,4))


ohe <- one.hot.encoder$new()


encoded_df <- ohe$fit_transform(df)

print(encoded_df)
```

```{r}
df <- data.frame(
  weight = c(80, 50, 75, NA),
  height = c(180, 160, NA, 175)
)

imputer <- SimpleQuantiImputer$new()

imputer$initialize(imputation_type = "median")

imputer$fit_transform(df, names(df))

```

```{r}
df <- data.frame(
  color = c("red", "blue", "green", "red", NA),
  size = c("small", "medium", NA, "medium", "large")
)

imputer <- SimpleQualiImputer$new()

imputer$initialize(imputation_type = "probability")

imputer$fit_transform(df, names(df))

```


